### ISSUE TITLE
StructureError for unauthorized type when using a list of CustomTypes

### ISSUE THREAD

**Issue by panchr** [namlook/mongokit#231]
I receive a `StructureError` when trying to set a structure field to a list of objects that inherit from `CustomType`. Here is my model structure, simplified:

```python
import mongokit
from bson.objectid import ObjectId

class Model(mongokit.Document):
    # a bunch of shared methods/static values reside here
    pass

class CustomTypeBase(mongokit.CustomType):
    # more configuration for custom types
    pass

class Gamestate(CustomTypeBase):
    mongo_type = [int]
    python_type = [int]
    init_type = list

class Game(Model):
     structure = {
         "players: [ObjectId], # this works fine
         "history": [Gamestate], # this will work fine if I use just Gamestate and not [Gamestate]
         }
```

I believe this is a bug because the schema is valid; storing a list of custom types should be possible, especially because my custom type inherits from `mongokit.CustomType`.

Here is my traceback (part of unit tests run with `nose`):
```
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\nose\loader.py", line 414, in loadTestsFro
mName
    addr.filename, addr.module)
  File "C:\Python27\lib\site-packages\nose\importer.py", line 47, in importFromP
ath
    return self.importFromDir(dir_path, fqname)
  File "C:\Python27\lib\site-packages\nose\importer.py", line 94, in importFromD
ir
    mod = load_module(part_fqname, fh, filename, desc)
  File "some_path\test_models\test_game.py", line 8, in <module>
    from models.game import Game
  File "some_path\models\game.py", line 9, in <module>
    class Game(Model):
  File "C:\Python27\lib\site-packages\mongokit\document.py", line 71, in __new__

    return SchemaProperties.__new__(cls, name, bases, attrs)
  File "C:\Python27\lib\site-packages\mongokit\schema_document.py", line 188, in
 __new__
    base._validate_structure(attrs['structure'], name, attrs.get('authorized_typ
es'))
  File "C:\Python27\lib\site-packages\mongokit\schema_document.py", line 549, in
 _validate_structure
    __validate_structure(structure, name, authorized_types)
  File "C:\Python27\lib\site-packages\mongokit\schema_document.py", line 496, in
 __validate_structure
    __validate_structure(struct[key], name, authorized_types)
  File "C:\Python27\lib\site-packages\mongokit\schema_document.py", line 523, in
 __validate_structure
    __validate_structure(item, name, authorized_types)
  File "C:\Python27\lib\site-packages\mongokit\schema_document.py", line 478, in
 __validate_structure
    raise StructureError("%s: %s is not an authorized type" % (name, struct))
StructureError: Game: <class 'models.state.Gamestate'> is not an authorized type
```

**Comment by panchr** [comment]
The proper way to use `CustomTypes` turned out to be `"history": [Gamestate()]`,
