### ISSUE TITLE
mogokit support python3

### ISSUE THREAD

**Issue by wenbindu** [namlook/mongokit#255]
when the mongokit can support python3

**Comment by domenicomonaco** [comment]
I've same question. I've installed MongoKit with pip3 and it's installed correctly but when I try to execute I've error in some "cursor Import":

```
Traceback (most recent call last):
  File "/.... file.py", line 5, in <module>
    from mongokit import *
  File "/usr/local/lib/python3.7/site-packages/mongokit/__init__.py", line 31, in <module>
    from cursor import Cursor
ModuleNotFoundError: No module named 'cursor'

Process finished with exit code 1
```

**Comment by Windfarer** [comment]
We have ported this great project to python 3 and pymongo 3, try this out. https://github.com/Windfarer/mongokit-ng
